# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/peta/devel/rlabs/phase5_ii

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/peta/devel/rlabs/phase5_ii

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/peta/devel/rlabs/phase5_ii/CMakeFiles /home/peta/devel/rlabs/phase5_ii/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/peta/devel/rlabs/phase5_ii/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tools

# Build rule for target.
tools: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tools
.PHONY : tools

# fast build rule for target.
tools/fast:
	$(MAKE) -f CMakeFiles/tools.dir/build.make CMakeFiles/tools.dir/build
.PHONY : tools/fast

#=============================================================================
# Target rules for targets named scripts

# Build rule for target.
scripts: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scripts
.PHONY : scripts

# fast build rule for target.
scripts/fast:
	$(MAKE) -f CMakeFiles/scripts.dir/build.make CMakeFiles/scripts.dir/build
.PHONY : scripts/fast

#=============================================================================
# Target rules for targets named benchmarks

# Build rule for target.
benchmarks: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 benchmarks
.PHONY : benchmarks

# fast build rule for target.
benchmarks/fast:
	$(MAKE) -f CMakeFiles/benchmarks.dir/build.make CMakeFiles/benchmarks.dir/build
.PHONY : benchmarks/fast

#=============================================================================
# Target rules for targets named dependencies

# Build rule for target.
dependencies: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dependencies
.PHONY : dependencies

# fast build rule for target.
dependencies/fast:
	$(MAKE) -f CMakeFiles/dependencies.dir/build.make CMakeFiles/dependencies.dir/build
.PHONY : dependencies/fast

#=============================================================================
# Target rules for targets named setup-build-dir

# Build rule for target.
setup-build-dir: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 setup-build-dir
.PHONY : setup-build-dir

# fast build rule for target.
setup-build-dir/fast:
	$(MAKE) -f CMakeFiles/setup-build-dir.dir/build.make CMakeFiles/setup-build-dir.dir/build
.PHONY : setup-build-dir/fast

#=============================================================================
# Target rules for targets named default-gnur

# Build rule for target.
default-gnur: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 default-gnur
.PHONY : default-gnur

# fast build rule for target.
default-gnur/fast:
	$(MAKE) -f CMakeFiles/default-gnur.dir/build.make CMakeFiles/default-gnur.dir/build
.PHONY : default-gnur/fast

#=============================================================================
# Target rules for targets named rir

# Build rule for target.
rir: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rir
.PHONY : rir

# fast build rule for target.
rir/fast:
	$(MAKE) -f CMakeFiles/rir.dir/build.make CMakeFiles/rir.dir/build
.PHONY : rir/fast

#=============================================================================
# Target rules for targets named setup

# Build rule for target.
setup: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 setup
.PHONY : setup

# fast build rule for target.
setup/fast:
	$(MAKE) -f CMakeFiles/setup.dir/build.make CMakeFiles/setup.dir/build
.PHONY : setup/fast

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/build
.PHONY : tests/fast

#=============================================================================
# Target rules for targets named rpkg

# Build rule for target.
rpkg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rpkg
.PHONY : rpkg

# fast build rule for target.
rpkg/fast:
	$(MAKE) -f CMakeFiles/rpkg.dir/build.make CMakeFiles/rpkg.dir/build
.PHONY : rpkg/fast

#=============================================================================
# Target rules for targets named rpkg_check

# Build rule for target.
rpkg_check: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rpkg_check
.PHONY : rpkg_check

# fast build rule for target.
rpkg_check/fast:
	$(MAKE) -f CMakeFiles/rpkg_check.dir/build.make CMakeFiles/rpkg_check.dir/build
.PHONY : rpkg_check/fast

#=============================================================================
# Target rules for targets named rpkg_install

# Build rule for target.
rpkg_install: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rpkg_install
.PHONY : rpkg_install

# fast build rule for target.
rpkg_install/fast:
	$(MAKE) -f CMakeFiles/rpkg_install.dir/build.make CMakeFiles/rpkg_install.dir/build
.PHONY : rpkg_install/fast

rir/src/R/RList.o: rir/src/R/RList.cpp.o

.PHONY : rir/src/R/RList.o

# target to build an object file
rir/src/R/RList.cpp.o:
	$(MAKE) -f CMakeFiles/rir.dir/build.make CMakeFiles/rir.dir/rir/src/R/RList.cpp.o
.PHONY : rir/src/R/RList.cpp.o

rir/src/R/RList.i: rir/src/R/RList.cpp.i

.PHONY : rir/src/R/RList.i

# target to preprocess a source file
rir/src/R/RList.cpp.i:
	$(MAKE) -f CMakeFiles/rir.dir/build.make CMakeFiles/rir.dir/rir/src/R/RList.cpp.i
.PHONY : rir/src/R/RList.cpp.i

rir/src/R/RList.s: rir/src/R/RList.cpp.s

.PHONY : rir/src/R/RList.s

# target to generate assembly for a file
rir/src/R/RList.cpp.s:
	$(MAKE) -f CMakeFiles/rir.dir/build.make CMakeFiles/rir.dir/rir/src/R/RList.cpp.s
.PHONY : rir/src/R/RList.cpp.s

rir/src/R/RVector.o: rir/src/R/RVector.cpp.o

.PHONY : rir/src/R/RVector.o

# target to build an object file
rir/src/R/RVector.cpp.o:
	$(MAKE) -f CMakeFiles/rir.dir/build.make CMakeFiles/rir.dir/rir/src/R/RVector.cpp.o
.PHONY : rir/src/R/RVector.cpp.o

rir/src/R/RVector.i: rir/src/R/RVector.cpp.i

.PHONY : rir/src/R/RVector.i

# target to preprocess a source file
rir/src/R/RVector.cpp.i:
	$(MAKE) -f CMakeFiles/rir.dir/build.make CMakeFiles/rir.dir/rir/src/R/RVector.cpp.i
.PHONY : rir/src/R/RVector.cpp.i

rir/src/R/RVector.s: rir/src/R/RVector.cpp.s

.PHONY : rir/src/R/RVector.s

# target to generate assembly for a file
rir/src/R/RVector.cpp.s:
	$(MAKE) -f CMakeFiles/rir.dir/build.make CMakeFiles/rir.dir/rir/src/R/RVector.cpp.s
.PHONY : rir/src/R/RVector.cpp.s

rir/src/R/Sexp.o: rir/src/R/Sexp.cpp.o

.PHONY : rir/src/R/Sexp.o

# target to build an object file
rir/src/R/Sexp.cpp.o:
	$(MAKE) -f CMakeFiles/rir.dir/build.make CMakeFiles/rir.dir/rir/src/R/Sexp.cpp.o
.PHONY : rir/src/R/Sexp.cpp.o

rir/src/R/Sexp.i: rir/src/R/Sexp.cpp.i

.PHONY : rir/src/R/Sexp.i

# target to preprocess a source file
rir/src/R/Sexp.cpp.i:
	$(MAKE) -f CMakeFiles/rir.dir/build.make CMakeFiles/rir.dir/rir/src/R/Sexp.cpp.i
.PHONY : rir/src/R/Sexp.cpp.i

rir/src/R/Sexp.s: rir/src/R/Sexp.cpp.s

.PHONY : rir/src/R/Sexp.s

# target to generate assembly for a file
rir/src/R/Sexp.cpp.s:
	$(MAKE) -f CMakeFiles/rir.dir/build.make CMakeFiles/rir.dir/rir/src/R/Sexp.cpp.s
.PHONY : rir/src/R/Sexp.cpp.s

rir/src/R/Symbols.o: rir/src/R/Symbols.cpp.o

.PHONY : rir/src/R/Symbols.o

# target to build an object file
rir/src/R/Symbols.cpp.o:
	$(MAKE) -f CMakeFiles/rir.dir/build.make CMakeFiles/rir.dir/rir/src/R/Symbols.cpp.o
.PHONY : rir/src/R/Symbols.cpp.o

rir/src/R/Symbols.i: rir/src/R/Symbols.cpp.i

.PHONY : rir/src/R/Symbols.i

# target to preprocess a source file
rir/src/R/Symbols.cpp.i:
	$(MAKE) -f CMakeFiles/rir.dir/build.make CMakeFiles/rir.dir/rir/src/R/Symbols.cpp.i
.PHONY : rir/src/R/Symbols.cpp.i

rir/src/R/Symbols.s: rir/src/R/Symbols.cpp.s

.PHONY : rir/src/R/Symbols.s

# target to generate assembly for a file
rir/src/R/Symbols.cpp.s:
	$(MAKE) -f CMakeFiles/rir.dir/build.make CMakeFiles/rir.dir/rir/src/R/Symbols.cpp.s
.PHONY : rir/src/R/Symbols.cpp.s

rir/src/api.o: rir/src/api.cpp.o

.PHONY : rir/src/api.o

# target to build an object file
rir/src/api.cpp.o:
	$(MAKE) -f CMakeFiles/rir.dir/build.make CMakeFiles/rir.dir/rir/src/api.cpp.o
.PHONY : rir/src/api.cpp.o

rir/src/api.i: rir/src/api.cpp.i

.PHONY : rir/src/api.i

# target to preprocess a source file
rir/src/api.cpp.i:
	$(MAKE) -f CMakeFiles/rir.dir/build.make CMakeFiles/rir.dir/rir/src/api.cpp.i
.PHONY : rir/src/api.cpp.i

rir/src/api.s: rir/src/api.cpp.s

.PHONY : rir/src/api.s

# target to generate assembly for a file
rir/src/api.cpp.s:
	$(MAKE) -f CMakeFiles/rir.dir/build.make CMakeFiles/rir.dir/rir/src/api.cpp.s
.PHONY : rir/src/api.cpp.s

rir/src/interpreter/deoptimizer.o: rir/src/interpreter/deoptimizer.cpp.o

.PHONY : rir/src/interpreter/deoptimizer.o

# target to build an object file
rir/src/interpreter/deoptimizer.cpp.o:
	$(MAKE) -f CMakeFiles/rir.dir/build.make CMakeFiles/rir.dir/rir/src/interpreter/deoptimizer.cpp.o
.PHONY : rir/src/interpreter/deoptimizer.cpp.o

rir/src/interpreter/deoptimizer.i: rir/src/interpreter/deoptimizer.cpp.i

.PHONY : rir/src/interpreter/deoptimizer.i

# target to preprocess a source file
rir/src/interpreter/deoptimizer.cpp.i:
	$(MAKE) -f CMakeFiles/rir.dir/build.make CMakeFiles/rir.dir/rir/src/interpreter/deoptimizer.cpp.i
.PHONY : rir/src/interpreter/deoptimizer.cpp.i

rir/src/interpreter/deoptimizer.s: rir/src/interpreter/deoptimizer.cpp.s

.PHONY : rir/src/interpreter/deoptimizer.s

# target to generate assembly for a file
rir/src/interpreter/deoptimizer.cpp.s:
	$(MAKE) -f CMakeFiles/rir.dir/build.make CMakeFiles/rir.dir/rir/src/interpreter/deoptimizer.cpp.s
.PHONY : rir/src/interpreter/deoptimizer.cpp.s

rir/src/interpreter/interp.o: rir/src/interpreter/interp.cpp.o

.PHONY : rir/src/interpreter/interp.o

# target to build an object file
rir/src/interpreter/interp.cpp.o:
	$(MAKE) -f CMakeFiles/rir.dir/build.make CMakeFiles/rir.dir/rir/src/interpreter/interp.cpp.o
.PHONY : rir/src/interpreter/interp.cpp.o

rir/src/interpreter/interp.i: rir/src/interpreter/interp.cpp.i

.PHONY : rir/src/interpreter/interp.i

# target to preprocess a source file
rir/src/interpreter/interp.cpp.i:
	$(MAKE) -f CMakeFiles/rir.dir/build.make CMakeFiles/rir.dir/rir/src/interpreter/interp.cpp.i
.PHONY : rir/src/interpreter/interp.cpp.i

rir/src/interpreter/interp.s: rir/src/interpreter/interp.cpp.s

.PHONY : rir/src/interpreter/interp.s

# target to generate assembly for a file
rir/src/interpreter/interp.cpp.s:
	$(MAKE) -f CMakeFiles/rir.dir/build.make CMakeFiles/rir.dir/rir/src/interpreter/interp.cpp.s
.PHONY : rir/src/interpreter/interp.cpp.s

rir/src/interpreter/interp_context.o: rir/src/interpreter/interp_context.cpp.o

.PHONY : rir/src/interpreter/interp_context.o

# target to build an object file
rir/src/interpreter/interp_context.cpp.o:
	$(MAKE) -f CMakeFiles/rir.dir/build.make CMakeFiles/rir.dir/rir/src/interpreter/interp_context.cpp.o
.PHONY : rir/src/interpreter/interp_context.cpp.o

rir/src/interpreter/interp_context.i: rir/src/interpreter/interp_context.cpp.i

.PHONY : rir/src/interpreter/interp_context.i

# target to preprocess a source file
rir/src/interpreter/interp_context.cpp.i:
	$(MAKE) -f CMakeFiles/rir.dir/build.make CMakeFiles/rir.dir/rir/src/interpreter/interp_context.cpp.i
.PHONY : rir/src/interpreter/interp_context.cpp.i

rir/src/interpreter/interp_context.s: rir/src/interpreter/interp_context.cpp.s

.PHONY : rir/src/interpreter/interp_context.s

# target to generate assembly for a file
rir/src/interpreter/interp_context.cpp.s:
	$(MAKE) -f CMakeFiles/rir.dir/build.make CMakeFiles/rir.dir/rir/src/interpreter/interp_context.cpp.s
.PHONY : rir/src/interpreter/interp_context.cpp.s

rir/src/interpreter/runtime.o: rir/src/interpreter/runtime.cpp.o

.PHONY : rir/src/interpreter/runtime.o

# target to build an object file
rir/src/interpreter/runtime.cpp.o:
	$(MAKE) -f CMakeFiles/rir.dir/build.make CMakeFiles/rir.dir/rir/src/interpreter/runtime.cpp.o
.PHONY : rir/src/interpreter/runtime.cpp.o

rir/src/interpreter/runtime.i: rir/src/interpreter/runtime.cpp.i

.PHONY : rir/src/interpreter/runtime.i

# target to preprocess a source file
rir/src/interpreter/runtime.cpp.i:
	$(MAKE) -f CMakeFiles/rir.dir/build.make CMakeFiles/rir.dir/rir/src/interpreter/runtime.cpp.i
.PHONY : rir/src/interpreter/runtime.cpp.i

rir/src/interpreter/runtime.s: rir/src/interpreter/runtime.cpp.s

.PHONY : rir/src/interpreter/runtime.s

# target to generate assembly for a file
rir/src/interpreter/runtime.cpp.s:
	$(MAKE) -f CMakeFiles/rir.dir/build.make CMakeFiles/rir.dir/rir/src/interpreter/runtime.cpp.s
.PHONY : rir/src/interpreter/runtime.cpp.s

rir/src/ir/BC.o: rir/src/ir/BC.cpp.o

.PHONY : rir/src/ir/BC.o

# target to build an object file
rir/src/ir/BC.cpp.o:
	$(MAKE) -f CMakeFiles/rir.dir/build.make CMakeFiles/rir.dir/rir/src/ir/BC.cpp.o
.PHONY : rir/src/ir/BC.cpp.o

rir/src/ir/BC.i: rir/src/ir/BC.cpp.i

.PHONY : rir/src/ir/BC.i

# target to preprocess a source file
rir/src/ir/BC.cpp.i:
	$(MAKE) -f CMakeFiles/rir.dir/build.make CMakeFiles/rir.dir/rir/src/ir/BC.cpp.i
.PHONY : rir/src/ir/BC.cpp.i

rir/src/ir/BC.s: rir/src/ir/BC.cpp.s

.PHONY : rir/src/ir/BC.s

# target to generate assembly for a file
rir/src/ir/BC.cpp.s:
	$(MAKE) -f CMakeFiles/rir.dir/build.make CMakeFiles/rir.dir/rir/src/ir/BC.cpp.s
.PHONY : rir/src/ir/BC.cpp.s

rir/src/ir/CodeEditor.o: rir/src/ir/CodeEditor.cpp.o

.PHONY : rir/src/ir/CodeEditor.o

# target to build an object file
rir/src/ir/CodeEditor.cpp.o:
	$(MAKE) -f CMakeFiles/rir.dir/build.make CMakeFiles/rir.dir/rir/src/ir/CodeEditor.cpp.o
.PHONY : rir/src/ir/CodeEditor.cpp.o

rir/src/ir/CodeEditor.i: rir/src/ir/CodeEditor.cpp.i

.PHONY : rir/src/ir/CodeEditor.i

# target to preprocess a source file
rir/src/ir/CodeEditor.cpp.i:
	$(MAKE) -f CMakeFiles/rir.dir/build.make CMakeFiles/rir.dir/rir/src/ir/CodeEditor.cpp.i
.PHONY : rir/src/ir/CodeEditor.cpp.i

rir/src/ir/CodeEditor.s: rir/src/ir/CodeEditor.cpp.s

.PHONY : rir/src/ir/CodeEditor.s

# target to generate assembly for a file
rir/src/ir/CodeEditor.cpp.s:
	$(MAKE) -f CMakeFiles/rir.dir/build.make CMakeFiles/rir.dir/rir/src/ir/CodeEditor.cpp.s
.PHONY : rir/src/ir/CodeEditor.cpp.s

rir/src/ir/CodeVerifier.o: rir/src/ir/CodeVerifier.cpp.o

.PHONY : rir/src/ir/CodeVerifier.o

# target to build an object file
rir/src/ir/CodeVerifier.cpp.o:
	$(MAKE) -f CMakeFiles/rir.dir/build.make CMakeFiles/rir.dir/rir/src/ir/CodeVerifier.cpp.o
.PHONY : rir/src/ir/CodeVerifier.cpp.o

rir/src/ir/CodeVerifier.i: rir/src/ir/CodeVerifier.cpp.i

.PHONY : rir/src/ir/CodeVerifier.i

# target to preprocess a source file
rir/src/ir/CodeVerifier.cpp.i:
	$(MAKE) -f CMakeFiles/rir.dir/build.make CMakeFiles/rir.dir/rir/src/ir/CodeVerifier.cpp.i
.PHONY : rir/src/ir/CodeVerifier.cpp.i

rir/src/ir/CodeVerifier.s: rir/src/ir/CodeVerifier.cpp.s

.PHONY : rir/src/ir/CodeVerifier.s

# target to generate assembly for a file
rir/src/ir/CodeVerifier.cpp.s:
	$(MAKE) -f CMakeFiles/rir.dir/build.make CMakeFiles/rir.dir/rir/src/ir/CodeVerifier.cpp.s
.PHONY : rir/src/ir/CodeVerifier.cpp.s

rir/src/ir/Compiler.o: rir/src/ir/Compiler.cpp.o

.PHONY : rir/src/ir/Compiler.o

# target to build an object file
rir/src/ir/Compiler.cpp.o:
	$(MAKE) -f CMakeFiles/rir.dir/build.make CMakeFiles/rir.dir/rir/src/ir/Compiler.cpp.o
.PHONY : rir/src/ir/Compiler.cpp.o

rir/src/ir/Compiler.i: rir/src/ir/Compiler.cpp.i

.PHONY : rir/src/ir/Compiler.i

# target to preprocess a source file
rir/src/ir/Compiler.cpp.i:
	$(MAKE) -f CMakeFiles/rir.dir/build.make CMakeFiles/rir.dir/rir/src/ir/Compiler.cpp.i
.PHONY : rir/src/ir/Compiler.cpp.i

rir/src/ir/Compiler.s: rir/src/ir/Compiler.cpp.s

.PHONY : rir/src/ir/Compiler.s

# target to generate assembly for a file
rir/src/ir/Compiler.cpp.s:
	$(MAKE) -f CMakeFiles/rir.dir/build.make CMakeFiles/rir.dir/rir/src/ir/Compiler.cpp.s
.PHONY : rir/src/ir/Compiler.cpp.s

rir/src/ir/Optimizer.o: rir/src/ir/Optimizer.cpp.o

.PHONY : rir/src/ir/Optimizer.o

# target to build an object file
rir/src/ir/Optimizer.cpp.o:
	$(MAKE) -f CMakeFiles/rir.dir/build.make CMakeFiles/rir.dir/rir/src/ir/Optimizer.cpp.o
.PHONY : rir/src/ir/Optimizer.cpp.o

rir/src/ir/Optimizer.i: rir/src/ir/Optimizer.cpp.i

.PHONY : rir/src/ir/Optimizer.i

# target to preprocess a source file
rir/src/ir/Optimizer.cpp.i:
	$(MAKE) -f CMakeFiles/rir.dir/build.make CMakeFiles/rir.dir/rir/src/ir/Optimizer.cpp.i
.PHONY : rir/src/ir/Optimizer.cpp.i

rir/src/ir/Optimizer.s: rir/src/ir/Optimizer.cpp.s

.PHONY : rir/src/ir/Optimizer.s

# target to generate assembly for a file
rir/src/ir/Optimizer.cpp.s:
	$(MAKE) -f CMakeFiles/rir.dir/build.make CMakeFiles/rir.dir/rir/src/ir/Optimizer.cpp.s
.PHONY : rir/src/ir/Optimizer.cpp.s

rir/src/optimization/cp.o: rir/src/optimization/cp.cpp.o

.PHONY : rir/src/optimization/cp.o

# target to build an object file
rir/src/optimization/cp.cpp.o:
	$(MAKE) -f CMakeFiles/rir.dir/build.make CMakeFiles/rir.dir/rir/src/optimization/cp.cpp.o
.PHONY : rir/src/optimization/cp.cpp.o

rir/src/optimization/cp.i: rir/src/optimization/cp.cpp.i

.PHONY : rir/src/optimization/cp.i

# target to preprocess a source file
rir/src/optimization/cp.cpp.i:
	$(MAKE) -f CMakeFiles/rir.dir/build.make CMakeFiles/rir.dir/rir/src/optimization/cp.cpp.i
.PHONY : rir/src/optimization/cp.cpp.i

rir/src/optimization/cp.s: rir/src/optimization/cp.cpp.s

.PHONY : rir/src/optimization/cp.s

# target to generate assembly for a file
rir/src/optimization/cp.cpp.s:
	$(MAKE) -f CMakeFiles/rir.dir/build.make CMakeFiles/rir.dir/rir/src/optimization/cp.cpp.s
.PHONY : rir/src/optimization/cp.cpp.s

rir/src/runtime/Code.o: rir/src/runtime/Code.cpp.o

.PHONY : rir/src/runtime/Code.o

# target to build an object file
rir/src/runtime/Code.cpp.o:
	$(MAKE) -f CMakeFiles/rir.dir/build.make CMakeFiles/rir.dir/rir/src/runtime/Code.cpp.o
.PHONY : rir/src/runtime/Code.cpp.o

rir/src/runtime/Code.i: rir/src/runtime/Code.cpp.i

.PHONY : rir/src/runtime/Code.i

# target to preprocess a source file
rir/src/runtime/Code.cpp.i:
	$(MAKE) -f CMakeFiles/rir.dir/build.make CMakeFiles/rir.dir/rir/src/runtime/Code.cpp.i
.PHONY : rir/src/runtime/Code.cpp.i

rir/src/runtime/Code.s: rir/src/runtime/Code.cpp.s

.PHONY : rir/src/runtime/Code.s

# target to generate assembly for a file
rir/src/runtime/Code.cpp.s:
	$(MAKE) -f CMakeFiles/rir.dir/build.make CMakeFiles/rir.dir/rir/src/runtime/Code.cpp.s
.PHONY : rir/src/runtime/Code.cpp.s

rir/src/tests/console.o: rir/src/tests/console.cpp.o

.PHONY : rir/src/tests/console.o

# target to build an object file
rir/src/tests/console.cpp.o:
	$(MAKE) -f CMakeFiles/rir.dir/build.make CMakeFiles/rir.dir/rir/src/tests/console.cpp.o
.PHONY : rir/src/tests/console.cpp.o

rir/src/tests/console.i: rir/src/tests/console.cpp.i

.PHONY : rir/src/tests/console.i

# target to preprocess a source file
rir/src/tests/console.cpp.i:
	$(MAKE) -f CMakeFiles/rir.dir/build.make CMakeFiles/rir.dir/rir/src/tests/console.cpp.i
.PHONY : rir/src/tests/console.cpp.i

rir/src/tests/console.s: rir/src/tests/console.cpp.s

.PHONY : rir/src/tests/console.s

# target to generate assembly for a file
rir/src/tests/console.cpp.s:
	$(MAKE) -f CMakeFiles/rir.dir/build.make CMakeFiles/rir.dir/rir/src/tests/console.cpp.s
.PHONY : rir/src/tests/console.cpp.s

rir/src/tests/dispatchers.o: rir/src/tests/dispatchers.cpp.o

.PHONY : rir/src/tests/dispatchers.o

# target to build an object file
rir/src/tests/dispatchers.cpp.o:
	$(MAKE) -f CMakeFiles/rir.dir/build.make CMakeFiles/rir.dir/rir/src/tests/dispatchers.cpp.o
.PHONY : rir/src/tests/dispatchers.cpp.o

rir/src/tests/dispatchers.i: rir/src/tests/dispatchers.cpp.i

.PHONY : rir/src/tests/dispatchers.i

# target to preprocess a source file
rir/src/tests/dispatchers.cpp.i:
	$(MAKE) -f CMakeFiles/rir.dir/build.make CMakeFiles/rir.dir/rir/src/tests/dispatchers.cpp.i
.PHONY : rir/src/tests/dispatchers.cpp.i

rir/src/tests/dispatchers.s: rir/src/tests/dispatchers.cpp.s

.PHONY : rir/src/tests/dispatchers.s

# target to generate assembly for a file
rir/src/tests/dispatchers.cpp.s:
	$(MAKE) -f CMakeFiles/rir.dir/build.make CMakeFiles/rir.dir/rir/src/tests/dispatchers.cpp.s
.PHONY : rir/src/tests/dispatchers.cpp.s

rir/src/tests/tests.o: rir/src/tests/tests.cpp.o

.PHONY : rir/src/tests/tests.o

# target to build an object file
rir/src/tests/tests.cpp.o:
	$(MAKE) -f CMakeFiles/rir.dir/build.make CMakeFiles/rir.dir/rir/src/tests/tests.cpp.o
.PHONY : rir/src/tests/tests.cpp.o

rir/src/tests/tests.i: rir/src/tests/tests.cpp.i

.PHONY : rir/src/tests/tests.i

# target to preprocess a source file
rir/src/tests/tests.cpp.i:
	$(MAKE) -f CMakeFiles/rir.dir/build.make CMakeFiles/rir.dir/rir/src/tests/tests.cpp.i
.PHONY : rir/src/tests/tests.cpp.i

rir/src/tests/tests.s: rir/src/tests/tests.cpp.s

.PHONY : rir/src/tests/tests.s

# target to generate assembly for a file
rir/src/tests/tests.cpp.s:
	$(MAKE) -f CMakeFiles/rir.dir/build.make CMakeFiles/rir.dir/rir/src/tests/tests.cpp.s
.PHONY : rir/src/tests/tests.cpp.s

rir/src/utils/Pool.o: rir/src/utils/Pool.cpp.o

.PHONY : rir/src/utils/Pool.o

# target to build an object file
rir/src/utils/Pool.cpp.o:
	$(MAKE) -f CMakeFiles/rir.dir/build.make CMakeFiles/rir.dir/rir/src/utils/Pool.cpp.o
.PHONY : rir/src/utils/Pool.cpp.o

rir/src/utils/Pool.i: rir/src/utils/Pool.cpp.i

.PHONY : rir/src/utils/Pool.i

# target to preprocess a source file
rir/src/utils/Pool.cpp.i:
	$(MAKE) -f CMakeFiles/rir.dir/build.make CMakeFiles/rir.dir/rir/src/utils/Pool.cpp.i
.PHONY : rir/src/utils/Pool.cpp.i

rir/src/utils/Pool.s: rir/src/utils/Pool.cpp.s

.PHONY : rir/src/utils/Pool.s

# target to generate assembly for a file
rir/src/utils/Pool.cpp.s:
	$(MAKE) -f CMakeFiles/rir.dir/build.make CMakeFiles/rir.dir/rir/src/utils/Pool.cpp.s
.PHONY : rir/src/utils/Pool.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... tools"
	@echo "... scripts"
	@echo "... benchmarks"
	@echo "... dependencies"
	@echo "... setup-build-dir"
	@echo "... default-gnur"
	@echo "... rir"
	@echo "... setup"
	@echo "... tests"
	@echo "... rpkg"
	@echo "... rpkg_check"
	@echo "... rpkg_install"
	@echo "... rir/src/R/RList.o"
	@echo "... rir/src/R/RList.i"
	@echo "... rir/src/R/RList.s"
	@echo "... rir/src/R/RVector.o"
	@echo "... rir/src/R/RVector.i"
	@echo "... rir/src/R/RVector.s"
	@echo "... rir/src/R/Sexp.o"
	@echo "... rir/src/R/Sexp.i"
	@echo "... rir/src/R/Sexp.s"
	@echo "... rir/src/R/Symbols.o"
	@echo "... rir/src/R/Symbols.i"
	@echo "... rir/src/R/Symbols.s"
	@echo "... rir/src/api.o"
	@echo "... rir/src/api.i"
	@echo "... rir/src/api.s"
	@echo "... rir/src/interpreter/deoptimizer.o"
	@echo "... rir/src/interpreter/deoptimizer.i"
	@echo "... rir/src/interpreter/deoptimizer.s"
	@echo "... rir/src/interpreter/interp.o"
	@echo "... rir/src/interpreter/interp.i"
	@echo "... rir/src/interpreter/interp.s"
	@echo "... rir/src/interpreter/interp_context.o"
	@echo "... rir/src/interpreter/interp_context.i"
	@echo "... rir/src/interpreter/interp_context.s"
	@echo "... rir/src/interpreter/runtime.o"
	@echo "... rir/src/interpreter/runtime.i"
	@echo "... rir/src/interpreter/runtime.s"
	@echo "... rir/src/ir/BC.o"
	@echo "... rir/src/ir/BC.i"
	@echo "... rir/src/ir/BC.s"
	@echo "... rir/src/ir/CodeEditor.o"
	@echo "... rir/src/ir/CodeEditor.i"
	@echo "... rir/src/ir/CodeEditor.s"
	@echo "... rir/src/ir/CodeVerifier.o"
	@echo "... rir/src/ir/CodeVerifier.i"
	@echo "... rir/src/ir/CodeVerifier.s"
	@echo "... rir/src/ir/Compiler.o"
	@echo "... rir/src/ir/Compiler.i"
	@echo "... rir/src/ir/Compiler.s"
	@echo "... rir/src/ir/Optimizer.o"
	@echo "... rir/src/ir/Optimizer.i"
	@echo "... rir/src/ir/Optimizer.s"
	@echo "... rir/src/optimization/cp.o"
	@echo "... rir/src/optimization/cp.i"
	@echo "... rir/src/optimization/cp.s"
	@echo "... rir/src/runtime/Code.o"
	@echo "... rir/src/runtime/Code.i"
	@echo "... rir/src/runtime/Code.s"
	@echo "... rir/src/tests/console.o"
	@echo "... rir/src/tests/console.i"
	@echo "... rir/src/tests/console.s"
	@echo "... rir/src/tests/dispatchers.o"
	@echo "... rir/src/tests/dispatchers.i"
	@echo "... rir/src/tests/dispatchers.s"
	@echo "... rir/src/tests/tests.o"
	@echo "... rir/src/tests/tests.i"
	@echo "... rir/src/tests/tests.s"
	@echo "... rir/src/utils/Pool.o"
	@echo "... rir/src/utils/Pool.i"
	@echo "... rir/src/utils/Pool.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

